#include "FailureReportUi.hpp"

#include "Version.hpp"

#include <cstdio>
#include <cstring>
#include <string>

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <shellapi.h>
#endif

namespace failureReportUi {
namespace {

#ifdef _WIN32
constexpr const char* kIssueNewUrlBase = "https://github.com/chetjones003/GoSurvey/issues/new";

constexpr int kClientWidthLogical  = 820;
constexpr int kClientHeightLogical = 560;

int ScalePx(int logicalPixels, UINT dpi) {
  return ::MulDiv(logicalPixels, static_cast<int>(dpi), 96);
}

UINT QueryUiDpi() {
  if (HMODULE user32 = ::GetModuleHandleW(L"user32.dll")) {
    using GetDpiForSystemFn = UINT(WINAPI*)();
    const auto fn = reinterpret_cast<GetDpiForSystemFn>(::GetProcAddress(user32, "GetDpiForSystem"));
    if (fn)
      return fn();
  }
  HDC hdc = ::GetDC(nullptr);
  const UINT dpi = hdc ? static_cast<UINT>(::GetDeviceCaps(hdc, LOGPIXELSY)) : 96U;
  if (hdc)
    ::ReleaseDC(nullptr, hdc);
  return dpi == 0 ? 96U : dpi;
}

std::wstring Utf8ToWide(const std::string& utf8) {
  if (utf8.empty())
    return std::wstring();
  const int need =
      ::MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), static_cast<int>(utf8.size()), nullptr, 0);
  if (need <= 0)
    return std::wstring();
  std::wstring out(static_cast<size_t>(need), L'\0');
  ::MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), static_cast<int>(utf8.size()), out.data(), need);
  return out;
}

HFONT CreatePointFont(const wchar_t* faceName, int pointSize, UINT dpi, bool bold) {
  const int height = -::MulDiv(pointSize, static_cast<int>(dpi), 72);
  return ::CreateFontW(height, 0, 0, 0, bold ? FW_SEMIBOLD : FW_NORMAL, FALSE, FALSE, FALSE,
                       DEFAULT_CHARSET, OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS, CLEARTYPE_QUALITY,
                       DEFAULT_PITCH | FF_DONTCARE, faceName);
}

HFONT CreateMonospaceReportFont(UINT dpi) {
  HFONT font = CreatePointFont(L"Cascadia Mono", 10, dpi, false);
  if (font)
    return font;
  font = CreatePointFont(L"Consolas", 10, dpi, false);
  if (font)
    return font;
  return CreatePointFont(L"Courier New", 10, dpi, false);
}

std::string UrlEncodeQueryUtf8(const std::string& utf8) {
  std::string out;
  out.reserve(utf8.size() + 16);
  for (unsigned char c : utf8) {
    const bool unreserved =
        (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' ||
        c == '_' || c == '.' || c == '~';
    if (unreserved) {
      out.push_back(static_cast<char>(c));
    } else if (c == ' ') {
      out += "%20";
    } else {
      char hex[4] = "%00";
      hex[1]      = "0123456789ABCDEF"[c >> 4];
      hex[2]      = "0123456789ABCDEF"[c & 0xF];
      out.append(hex, 3);
    }
  }
  return out;
}

bool CopyUtf8TextToClipboard(const std::string& utf8) {
  if (!::OpenClipboard(nullptr))
    return false;
  ::EmptyClipboard();
  const std::wstring wide = Utf8ToWide(utf8);
  if (wide.empty()) {
    ::CloseClipboard();
    return false;
  }
  const size_t bytes = (wide.size() + 1) * sizeof(wchar_t);
  HGLOBAL      mem   = ::GlobalAlloc(GMEM_MOVEABLE, bytes);
  if (!mem) {
    ::CloseClipboard();
    return false;
  }
  void* locked = ::GlobalLock(mem);
  if (!locked) {
    ::GlobalFree(mem);
    ::CloseClipboard();
    return false;
  }
  std::memcpy(locked, wide.c_str(), bytes);
  ::GlobalUnlock(mem);
  const bool set = ::SetClipboardData(CF_UNICODETEXT, mem) != nullptr;
  ::CloseClipboard();
  if (!set)
    ::GlobalFree(mem);
  return set;
}

void SendReportToGitHub(const std::string& reportUtf8) {
  const bool copied = CopyUtf8TextToClipboard(reportUtf8);
  std::string title = std::string("GoSurvey report (") + GOSURVEY_VERSION_FULL + ")";
  std::string body  = "### Failure report\n\n";
  body += "_(Auto-generated by GoSurvey — please submit if you need help.)_\n\n";
  body += "```\n";
  body += reportUtf8;
  body += "\n```\n";

  constexpr size_t kMaxBodyChars = 5200;
  if (body.size() > kMaxBodyChars) {
    body.resize(kMaxBodyChars);
    body += "\n...(truncated in URL — full report copied to clipboard)...\n";
  }

  const std::string url =
      std::string(kIssueNewUrlBase) + "?title=" + UrlEncodeQueryUtf8(title) + "&body=" +
      UrlEncodeQueryUtf8(body);
  const std::wstring urlW = Utf8ToWide(url);
  const HINSTANCE  rc =
      urlW.empty() ? nullptr
                   : ::ShellExecuteW(nullptr, L"open", urlW.c_str(), nullptr, nullptr, SW_SHOWNORMAL);
  const bool opened = rc != nullptr && reinterpret_cast<INT_PTR>(rc) > 32;

  std::wstring msg;
  if (copied && opened) {
    msg = L"The full report was copied to your clipboard.\n\n"
          L"Your browser should open GitHub so you can submit an issue. "
          L"Sign in to GitHub if prompted, review the text, and click Submit new issue.";
  } else if (copied) {
    msg = L"The full report was copied to your clipboard.\n\n"
          L"Could not open the browser automatically. Paste the report at:\n"
          L"https://github.com/chetjones003/GoSurvey/issues/new";
  } else if (opened) {
    msg = L"Your browser should open GitHub with a pre-filled issue.\n\n"
          L"Could not copy the report to the clipboard — copy the text from this window before "
          L"submitting.";
  } else {
    msg = L"Could not open the browser or copy to the clipboard.\n\n"
          L"Please copy the text from this window and open:\n"
          L"https://github.com/chetjones003/GoSurvey/issues/new";
  }
  ::MessageBoxW(nullptr, msg.c_str(), L"Send This Report", MB_OK | MB_ICONINFORMATION);
}

struct FailureDialogContext {
  std::string reportUtf8;
  std::wstring reportWide;
  UINT         dpi           = 96;
  int          margin        = 12;
  int          footerGap     = 10;
  int          buttonHeight  = 28;
  int          sendButtonW   = 160;
  int          closeButtonW  = 96;
  int          minOuterW     = 0;
  int          minOuterH     = 0;
  HFONT        fontUi        = nullptr;
  HFONT        fontReport    = nullptr;
  HWND         hwndEdit      = nullptr;
  HWND         hwndSend      = nullptr;
  HWND         hwndClose     = nullptr;
};

constexpr int kEditId  = 1001;
constexpr int kSendId  = 1002;
constexpr int kCloseId = 1003;

void ApplyFont(HWND hwnd, HFONT font) {
  if (hwnd && font)
    ::SendMessageW(hwnd, WM_SETFONT, reinterpret_cast<WPARAM>(font), TRUE);
}

void LayoutFailureDialog(HWND hwnd, FailureDialogContext* ctx) {
  if (!ctx || !ctx->hwndEdit)
    return;

  RECT client{};
  if (!::GetClientRect(hwnd, &client))
    return;

  const int cw = client.right - client.left;
  const int ch = client.bottom - client.top;
  const int m  = ctx->margin;
  const int footer =
      ctx->footerGap + ctx->buttonHeight + m;
  const int editH = ch - footer - m;
  if (editH < ScalePx(80, ctx->dpi))
    return;

  const int editW = cw - 2 * m;
  ::SetWindowPos(ctx->hwndEdit, nullptr, m, m, editW, editH, SWP_NOZORDER | SWP_NOACTIVATE);

  const int btnY = ch - m - ctx->buttonHeight;
  ::SetWindowPos(ctx->hwndSend, nullptr, m, btnY, ctx->sendButtonW, ctx->buttonHeight,
                 SWP_NOZORDER | SWP_NOACTIVATE);
  ::SetWindowPos(ctx->hwndClose, nullptr, cw - m - ctx->closeButtonW, btnY, ctx->closeButtonW,
                 ctx->buttonHeight, SWP_NOZORDER | SWP_NOACTIVATE);
}

LRESULT CALLBACK FailureWindowProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) {
  auto* ctx = reinterpret_cast<FailureDialogContext*>(::GetWindowLongPtrW(hwnd, GWLP_USERDATA));
  switch (msg) {
  case WM_CREATE: {
    const auto* create = reinterpret_cast<const CREATESTRUCTW*>(lParam);
    ctx                = reinterpret_cast<FailureDialogContext*>(create->lpCreateParams);
    ::SetWindowLongPtrW(hwnd, GWLP_USERDATA, reinterpret_cast<LONG_PTR>(ctx));
    if (!ctx)
      return -1;

    ctx->dpi = QueryUiDpi();
    ctx->margin       = ScalePx(14, ctx->dpi);
    ctx->footerGap    = ScalePx(12, ctx->dpi);
    ctx->buttonHeight = ScalePx(30, ctx->dpi);
    ctx->sendButtonW  = ScalePx(168, ctx->dpi);
    ctx->closeButtonW = ScalePx(100, ctx->dpi);

    ctx->fontUi     = CreatePointFont(L"Segoe UI", 9, ctx->dpi, false);
    ctx->fontReport = CreateMonospaceReportFont(ctx->dpi);

    const HINSTANCE inst = reinterpret_cast<HINSTANCE>(create->hInstance);

    ctx->hwndEdit = ::CreateWindowExW(
        WS_EX_CLIENTEDGE, L"EDIT", L"",
        WS_CHILD | WS_VISIBLE | ES_MULTILINE | ES_AUTOVSCROLL | ES_READONLY | WS_VSCROLL, 0, 0, 10,
        10, hwnd, reinterpret_cast<HMENU>(static_cast<INT_PTR>(kEditId)), inst, nullptr);

    ctx->hwndSend = ::CreateWindowExW(0, L"BUTTON", L"Send This Report",
                                      WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON, 0, 0, 10, 10, hwnd,
                                      reinterpret_cast<HMENU>(static_cast<INT_PTR>(kSendId)), inst,
                                      nullptr);

    ctx->hwndClose = ::CreateWindowExW(0, L"BUTTON", L"Close",
                                       WS_CHILD | WS_VISIBLE | BS_DEFPUSHBUTTON, 0, 0, 10, 10,
                                       hwnd, reinterpret_cast<HMENU>(static_cast<INT_PTR>(kCloseId)),
                                       inst, nullptr);

    ApplyFont(ctx->hwndEdit, ctx->fontReport);
    ApplyFont(ctx->hwndSend, ctx->fontUi);
    ApplyFont(ctx->hwndClose, ctx->fontUi);

    LayoutFailureDialog(hwnd, ctx);

    if (!ctx->reportWide.empty()) {
      ::SetWindowTextW(ctx->hwndEdit, ctx->reportWide.c_str());
      ::SendMessageW(ctx->hwndEdit, EM_FMTLINES, TRUE, 0);
    }

    if (ctx->hwndClose)
      ::SetFocus(ctx->hwndClose);
    return 0;
  }
  case WM_SIZE:
    LayoutFailureDialog(hwnd, ctx);
    if (ctx && ctx->hwndEdit)
      ::SendMessageW(ctx->hwndEdit, EM_FMTLINES, TRUE, 0);
    return 0;
  case WM_GETMINMAXINFO: {
    if (!ctx)
      break;
    auto* mmi = reinterpret_cast<MINMAXINFO*>(lParam);
    if (ctx->minOuterW > 0)
      mmi->ptMinTrackSize.x = ctx->minOuterW;
    if (ctx->minOuterH > 0)
      mmi->ptMinTrackSize.y = ctx->minOuterH;
    return 0;
  }
  case WM_COMMAND:
    if (LOWORD(wParam) == kSendId && ctx) {
      SendReportToGitHub(ctx->reportUtf8);
      return 0;
    }
    if (LOWORD(wParam) == kCloseId) {
      ::DestroyWindow(hwnd);
      return 0;
    }
    break;
  case WM_CLOSE:
    ::DestroyWindow(hwnd);
    return 0;
  case WM_DESTROY:
    if (ctx) {
      if (ctx->fontUi) {
        ::DeleteObject(ctx->fontUi);
        ctx->fontUi = nullptr;
      }
      if (ctx->fontReport) {
        ::DeleteObject(ctx->fontReport);
        ctx->fontReport = nullptr;
      }
    }
    ::PostQuitMessage(0);
    return 0;
  default:
    break;
  }
  return ::DefWindowProcW(hwnd, msg, wParam, lParam);
}

void CenterWindowOnPrimaryWorkArea(HWND hwnd, int outerW, int outerH) {
  int posX = 100;
  int posY = 100;
  if (HMONITOR mon = ::MonitorFromWindow(hwnd, MONITOR_DEFAULTTOPRIMARY)) {
    MONITORINFO mi{};
    mi.cbSize = sizeof(mi);
    if (::GetMonitorInfoW(mon, &mi)) {
      const RECT& wa = mi.rcWork;
      posX           = wa.left + (wa.right - wa.left - outerW) / 2;
      posY           = wa.top + (wa.bottom - wa.top - outerH) / 2;
    }
  }
  ::SetWindowPos(hwnd, nullptr, posX, posY, outerW, outerH, SWP_NOZORDER | SWP_NOACTIVATE);
}
#endif

}  // namespace

void ShowReportDialog(const wchar_t* windowTitle, const std::string& reportUtf8) {
#ifdef _WIN32
  FailureDialogContext ctx;
  ctx.reportUtf8  = reportUtf8;
  ctx.reportWide  = Utf8ToWide(reportUtf8);
  ctx.dpi         = QueryUiDpi();

  const wchar_t* kClass = L"GoSurveyFailureReportV2";
  HINSTANCE          inst = ::GetModuleHandleW(nullptr);
  static bool        registered = false;
  if (!registered) {
    WNDCLASSEXW wc{};
    wc.cbSize        = sizeof(wc);
    wc.lpfnWndProc   = FailureWindowProc;
    wc.hInstance     = inst;
    wc.lpszClassName = kClass;
    wc.hCursor       = ::LoadCursorW(nullptr, MAKEINTRESOURCEW(32512));
    wc.hbrBackground = reinterpret_cast<HBRUSH>(COLOR_WINDOW + 1);
    ::RegisterClassExW(&wc);
    registered = true;
  }

  const DWORD exStyle = WS_EX_APPWINDOW | WS_EX_DLGMODALFRAME;
  const DWORD style   = WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_THICKFRAME | WS_MINIMIZEBOX;

  const int clientW = ScalePx(kClientWidthLogical, ctx.dpi);
  const int clientH = ScalePx(kClientHeightLogical, ctx.dpi);
  RECT      wr{0, 0, clientW, clientH};
  ::AdjustWindowRectEx(&wr, style, FALSE, exStyle);
  const int outerW = wr.right - wr.left;
  const int outerH = wr.bottom - wr.top;
  ctx.minOuterW    = outerW;
  ctx.minOuterH    = outerH;

  const wchar_t* titleW =
      (windowTitle && windowTitle[0]) ? windowTitle : L"GoSurvey";

  HWND hwnd = ::CreateWindowExW(exStyle, kClass, titleW, style, CW_USEDEFAULT, CW_USEDEFAULT,
                                outerW, outerH, nullptr, nullptr, inst, &ctx);
  if (!hwnd) {
    ::MessageBoxW(nullptr, ctx.reportWide.c_str(), titleW, MB_OK | MB_ICONERROR);
    return;
  }

  CenterWindowOnPrimaryWorkArea(hwnd, outerW, outerH);
  ::ShowWindow(hwnd, SW_SHOW);
  ::UpdateWindow(hwnd);

  MSG message{};
  while (::GetMessageW(&message, nullptr, 0, 0) > 0) {
    if (!::IsDialogMessageW(hwnd, &message)) {
      ::TranslateMessage(&message);
      ::DispatchMessageW(&message);
    }
  }
#else
  (void)windowTitle;
  std::fprintf(stderr, "%s\n", reportUtf8.c_str());
#endif
}

}  // namespace failureReportUi
