#include "StartupFailure.hpp"

#include "AppPaths.hpp"
#include "Version.hpp"

#include <cstdio>
#include <cstring>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <string>

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <shellapi.h>
#endif

namespace startupFailure {
namespace {

#ifdef _WIN32
int         g_lastGlfwErrorCode = 0;
std::string g_lastGlfwErrorText;

constexpr const char* kIssueNewUrlBase = "https://github.com/chetjones003/GoSurvey/issues/new";

std::wstring Utf8ToWide(const std::string& utf8) {
  if (utf8.empty())
    return std::wstring();
  const int need =
      ::MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), static_cast<int>(utf8.size()), nullptr, 0);
  if (need <= 0)
    return std::wstring();
  std::wstring out(static_cast<size_t>(need), L'\0');
  ::MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), static_cast<int>(utf8.size()), out.data(), need);
  return out;
}

std::string StageSummary(Stage stage) {
  switch (stage) {
  case Stage::GlfwInit:
    return "GoSurvey could not initialize its display library (GLFW).";
  case Stage::GlfwCreateWindow:
    return "GoSurvey could not create a graphics window.\n\n"
           "This usually means OpenGL 3.3 is not available from your graphics driver. "
           "OpenGL is provided by your GPU driver (it is not a separate installer like Visual C++).\n\n"
           "Try: Windows Update (Optional updates → driver updates), or install the latest driver "
           "from your PC or GPU vendor. Remote desktop and virtual machines often need 3D "
           "acceleration enabled.";
  case Stage::OpenGlInit:
    return "GoSurvey could not initialize OpenGL 3.3 for drawing.\n\n"
           "Update your graphics driver, or in Settings → System try turning off Hardware "
           "Acceleration after you can open the app from a machine that works.";
  }
  return "GoSurvey could not start.";
}

/// Query-component encoding (UTF-8 in, ASCII percent-escapes out).
std::string UrlEncodeQueryUtf8(const std::string& utf8) {
  std::string out;
  out.reserve(utf8.size() + 16);
  for (unsigned char c : utf8) {
    const bool unreserved =
        (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' ||
        c == '_' || c == '.' || c == '~';
    if (unreserved) {
      out.push_back(static_cast<char>(c));
    } else if (c == ' ') {
      out += "%20";
    } else {
      char hex[4] = "%00";
      hex[1]      = "0123456789ABCDEF"[c >> 4];
      hex[2]      = "0123456789ABCDEF"[c & 0xF];
      out.append(hex, 3);
    }
  }
  return out;
}

bool CopyUtf8TextToClipboard(const std::string& utf8) {
  if (!::OpenClipboard(nullptr))
    return false;
  ::EmptyClipboard();
  const std::wstring wide = Utf8ToWide(utf8);
  if (wide.empty()) {
    ::CloseClipboard();
    return false;
  }
  const size_t bytes = (wide.size() + 1) * sizeof(wchar_t);
  HGLOBAL      mem   = ::GlobalAlloc(GMEM_MOVEABLE, bytes);
  if (!mem) {
    ::CloseClipboard();
    return false;
  }
  void* locked = ::GlobalLock(mem);
  if (!locked) {
    ::GlobalFree(mem);
    ::CloseClipboard();
    return false;
  }
  std::memcpy(locked, wide.c_str(), bytes);
  ::GlobalUnlock(mem);
  const bool set = ::SetClipboardData(CF_UNICODETEXT, mem) != nullptr;
  ::CloseClipboard();
  if (!set)
    ::GlobalFree(mem);
  return set;
}

std::string BuildGitHubNewIssueUrl(const std::string& reportUtf8) {
  std::string title = std::string("Startup failure (") + GOSURVEY_VERSION_FULL + ")";
  std::string body  = "### Startup failure report\n\n";
  body += "_(Auto-generated by GoSurvey — please submit if you need help.)_\n\n";
  body += "```\n";
  body += reportUtf8;
  body += "\n```\n";

  // Stay under common browser URL limits; the full report is always on the clipboard.
  constexpr size_t kMaxBodyChars = 5200;
  if (body.size() > kMaxBodyChars) {
    body.resize(kMaxBodyChars);
    body += "\n...(truncated in URL — full report copied to clipboard)...\n";
  }

  return std::string(kIssueNewUrlBase) + "?title=" + UrlEncodeQueryUtf8(title) + "&body=" +
         UrlEncodeQueryUtf8(body);
}

void SendReportToGitHub(const std::string& reportUtf8) {
  const bool copied = CopyUtf8TextToClipboard(reportUtf8);
  const std::string url = BuildGitHubNewIssueUrl(reportUtf8);
  const std::wstring urlW = Utf8ToWide(url);
  const HINSTANCE  rc =
      urlW.empty() ? nullptr
                   : ::ShellExecuteW(nullptr, L"open", urlW.c_str(), nullptr, nullptr, SW_SHOWNORMAL);
  const bool opened = rc != nullptr && reinterpret_cast<INT_PTR>(rc) > 32;

  std::wstring msg = L"";
  if (copied && opened) {
    msg = L"The full report was copied to your clipboard.\n\n"
          L"Your browser should open GitHub so you can submit an issue. "
          L"Sign in to GitHub if prompted, review the text, and click Submit new issue.";
  } else if (copied) {
    msg = L"The full report was copied to your clipboard.\n\n"
          L"Could not open the browser automatically. Paste the report at:\n"
          L"https://github.com/chetjones003/GoSurvey/issues/new";
  } else if (opened) {
    msg = L"Your browser should open GitHub with a pre-filled issue.\n\n"
          L"Could not copy the report to the clipboard — copy the text from this window before "
          L"submitting.";
  } else {
    msg = L"Could not open the browser or copy to the clipboard.\n\n"
          L"Please copy the text from this window and open:\n"
          L"https://github.com/chetjones003/GoSurvey/issues/new";
  }
  ::MessageBoxW(nullptr, msg.c_str(), L"Send This Report", MB_OK | MB_ICONINFORMATION);
}

struct FailureDialogContext {
  std::string reportUtf8;
};

constexpr int kEditId  = 1001;
constexpr int kSendId  = 1002;
constexpr int kCloseId = 1003;

LRESULT CALLBACK FailureWindowProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) {
  auto* ctx = reinterpret_cast<FailureDialogContext*>(::GetWindowLongPtrW(hwnd, GWLP_USERDATA));
  switch (msg) {
  case WM_CREATE: {
    const auto* create = reinterpret_cast<const CREATESTRUCTW*>(lParam);
    ::SetWindowLongPtrW(hwnd, GWLP_USERDATA, reinterpret_cast<LONG_PTR>(create->lpCreateParams));
    return 0;
  }
  case WM_COMMAND:
    if (LOWORD(wParam) == kSendId && ctx) {
      SendReportToGitHub(ctx->reportUtf8);
      return 0;
    }
    if (LOWORD(wParam) == kCloseId) {
      ::DestroyWindow(hwnd);
      return 0;
    }
    break;
  case WM_CLOSE:
    ::DestroyWindow(hwnd);
    return 0;
  case WM_DESTROY:
    ::PostQuitMessage(0);
    return 0;
  default:
    break;
  }
  return ::DefWindowProcW(hwnd, msg, wParam, lParam);
}

void ShowFailureDialog(const std::string& reportUtf8) {
  FailureDialogContext ctx;
  ctx.reportUtf8       = reportUtf8;

  const wchar_t* kClass = L"GoSurveyStartupFailureV1";
  HINSTANCE          inst = ::GetModuleHandleW(nullptr);
  static bool        registered = false;
  if (!registered) {
    WNDCLASSEXW wc{};
    wc.cbSize        = sizeof(wc);
    wc.lpfnWndProc   = FailureWindowProc;
    wc.hInstance     = inst;
    wc.lpszClassName = kClass;
    wc.hCursor       = ::LoadCursorW(nullptr, MAKEINTRESOURCEW(32512));  // IDC_ARROW
    wc.hbrBackground = reinterpret_cast<HBRUSH>(COLOR_WINDOW + 1);
    ::RegisterClassExW(&wc);
    registered = true;
  }

  const int winW = 720;
  const int winH = 420;
  int       posX = 100;
  int       posY = 100;
  if (HWND desktop = ::GetDesktopWindow()) {
    RECT rc{};
    if (::GetWindowRect(desktop, &rc)) {
      posX = rc.left + (rc.right - rc.left - winW) / 2;
      posY = rc.top + (rc.bottom - rc.top - winH) / 2;
    }
  }

  const std::wstring bodyW = Utf8ToWide(reportUtf8);

  HWND hwnd = ::CreateWindowExW(
      WS_EX_APPWINDOW | WS_EX_DLGMODALFRAME, kClass, L"GoSurvey could not start",
      WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU, posX, posY, winW, winH, nullptr, nullptr, inst,
      &ctx);
  if (!hwnd) {
    ::MessageBoxW(nullptr, bodyW.c_str(), L"GoSurvey could not start", MB_OK | MB_ICONERROR);
    return;
  }

  ::CreateWindowExW(WS_EX_CLIENTEDGE, L"EDIT", bodyW.c_str(),
                    WS_CHILD | WS_VISIBLE | ES_MULTILINE | ES_AUTOVSCROLL | ES_READONLY | WS_VSCROLL,
                    12, 12, winW - 36, winH - 72, hwnd, reinterpret_cast<HMENU>(static_cast<INT_PTR>(kEditId)),
                    inst, nullptr);

  ::CreateWindowExW(0, L"BUTTON", L"Send This Report", WS_CHILD | WS_VISIBLE, 12, winH - 52, 150, 28,
                    hwnd, reinterpret_cast<HMENU>(static_cast<INT_PTR>(kSendId)), inst, nullptr);

  HWND btnClose = ::CreateWindowExW(
      0, L"BUTTON", L"Close", WS_CHILD | WS_VISIBLE | BS_DEFPUSHBUTTON, winW - 108, winH - 52, 96,
      28, hwnd, reinterpret_cast<HMENU>(static_cast<INT_PTR>(kCloseId)), inst, nullptr);
  if (btnClose)
    ::SetFocus(btnClose);

  ::ShowWindow(hwnd, SW_SHOW);
  ::UpdateWindow(hwnd);

  MSG message{};
  while (::GetMessageW(&message, nullptr, 0, 0) > 0) {
    if (!::IsDialogMessageW(hwnd, &message)) {
      ::TranslateMessage(&message);
      ::DispatchMessageW(&message);
    }
  }
}
#endif  // _WIN32

std::filesystem::path StartupFailureLogPath() {
  const std::filesystem::path dir = UserDataDirectory();
  if (dir.empty())
    return std::filesystem::path("startup-failure.log");
  return dir / "startup-failure.log";
}

void WriteStartupFailureLog(Stage stage, const std::string& detailUtf8) {
  const std::filesystem::path logPath = StartupFailureLogPath();
  std::error_code             ec;
  if (!logPath.parent_path().empty())
    std::filesystem::create_directories(logPath.parent_path(), ec);

  std::ofstream out(logPath, std::ios::app);
  if (!out)
    return;

  const std::time_t t = std::time(nullptr);
  char              timeBuf[32] = "0000-00-00 00:00:00";
  struct tm         tmInfo{};
  if (localtime_s(&tmInfo, &t) == 0)
    std::strftime(timeBuf, sizeof(timeBuf), "%Y-%m-%d %H:%M:%S", &tmInfo);

  out << "---- " << timeBuf << " ----\n";
  out << "version: " << GOSURVEY_VERSION_FULL << "\n";
  out << "stage: " << static_cast<int>(stage) << "\n";
  out << StageSummary(stage) << "\n";
  if (!detailUtf8.empty())
    out << "detail: " << detailUtf8 << "\n";
#ifdef _WIN32
  if (g_lastGlfwErrorCode != 0 || !g_lastGlfwErrorText.empty()) {
    out << "last_glfw_error: " << g_lastGlfwErrorCode << " " << g_lastGlfwErrorText << "\n";
  }
#endif
  out << "log_file: " << logPath.u8string() << "\n\n";
}

}  // namespace

void NoteGlfwError(int code, const char* description) {
#ifdef _WIN32
  g_lastGlfwErrorCode = code;
  g_lastGlfwErrorText = (description && description[0]) ? description : std::string();
#endif
  (void)code;
  (void)description;
}

[[noreturn]] void FailAndShow(Stage stage, const std::string& detailUtf8) {
  WriteStartupFailureLog(stage, detailUtf8);

  const std::string summary = StageSummary(stage);
  std::string       body    = summary;
  if (!detailUtf8.empty()) {
    body += "\n\nTechnical detail:\n";
    body += detailUtf8;
  }
#ifdef _WIN32
  if (g_lastGlfwErrorCode != 0 || !g_lastGlfwErrorText.empty()) {
    body += "\n\nLast GLFW message:\n";
    body += std::to_string(g_lastGlfwErrorCode);
    body += ": ";
    body += g_lastGlfwErrorText;
  }
#endif
  body += "\n\nA copy of this report was appended to:\n";
  body += StartupFailureLogPath().u8string();
  body += "\n\nUse \"Send This Report\" to copy this text and open GitHub to file an issue.";

  std::fprintf(stderr, "%s\n", body.c_str());

#ifdef _WIN32
  ShowFailureDialog(body);
  ::ExitProcess(1);
#else
  std::exit(1);
#endif
}

}  // namespace startupFailure
